#!/usr/local/bin/python

# A script to compile the Thesis - Fayimora

import argparse
from os import system

parser = argparse.ArgumentParser(description='Utility or compiling the thesis')
parser.add_argument('-c', '--clean', action='store_true', default=False, help='Cleans the current directory')
parser.add_argument('-p', '--process')

args = parser.parse_args()

temp_files = ['*.aux', '*.bbl', '*.blg', '*.d', '*.fls', '*.ilg', '*.ind', '*.toc*', '*.lot*', '*.lof*', '*.log', '*.idx', '*.out*', '*.nlo', '*.nls']


def clean():
    """Clean directory"""

    print "Cleaning in progress..."
    for f in temp_files:
        system("rm -rf %s" % f)
    print "Done cleaning!"


def process(path):
    """Compile and generate PDF file"""
    print "Compiling the thesis..."
    system("pdflatex -interaction=nonstopmode %s" % path)

    idx, move = path.find('/'), False
    aux_path = path
    if idx != -1:
        aux_path, move = path[idx+1:], True

    system("bibtex %s" % aux_path)
    system("pdflatex -interaction=nonstopmode %s" % path)
    system("pdflatex -interaction=nonstopmode %s" % path)
    if move:
        system("mv %s.pdf %s" % (aux_path, aux_path))
    print "Done compiling thesis!"


if __name__ == '__main__':
    if args.clean:
        clean()
    else:
        process(args.process)

